name: Build Dev

on:
  push:
    branches:
      - main

jobs:
  release:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      # 检出 Git 仓库
      - name: Check out git repository
        uses: actions/checkout@v4.1.1
        with:
          fetch-depth: 0

       #安装 Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4.0.0
        with:
          node-version: "18.x"
      # 安装项目依赖
      - name: Install Dependencies
        run: | 
          npm install
          npm i hexo -g
      - name: 本地推送
        run: |
          hexo deploy
       #Deploy hexo blog website.
      - name: Deploy
        id: deploy
        uses: sma11black/hexo-action@v1.0.3
        with:
          deploy_key: ${{ secrets.DEPLOY_KEY }}
          user_name: jadehh  # (or delete this input setting to use bot account)
          user_email: jadehh@live.com  # (or delete this input setting to use bot account)
          commit_msg: ${{ github.event.head_commit.message }}  # (or delete this input setting to use hexo default settings)

