name: Build Dev

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          # If your repository depends on submodule, please see: https://github.com/actions/checkout
          submodules: recursive
      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          # Examples: 20, 18.19, >=16.20.2, lts/Iron, lts/Hydrogen, *, latest, current, node
          # Ref: https://github.com/actions/setup-node#supported-version-syntax
          node-version: '20'
      - name: Cache NPM dependencies
        uses: actions/cache@v4
        with:
          path: node_modules
          key: ${{ runner.OS }}-npm-cache
          restore-keys: |
            ${{ runner.OS }}-npm-cache
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
      - name: Add Git File
        run: |
          git config --global user.email "jadehh@live.com"
          git config --global user.name "jade"
          cd public
          git config --global init.defaultBranch master
          git init
          checkname=$(git rev-list --max-parents=0 HEAD)
          git checkout  $checkname -b dist  ##分支不存在用这个
          git add -A
          git commit -m  "${{ github.event.head_commit.message }}"


      - name: Upload Gitee branch
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GiteeToken }}
          repository: ${{ secrets.GiteePath }}
          directory: .
          branch: master
          force: true
          tags: true
          github_url: https://gitee.com
        env:
          GITHUB_ACTOR: jadehh


  deploy:
    #测试Deploy
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4